### ISSUE TITLE
Wrong method used 

### ISSUE THREAD

**Issue by samblacklock** [Cretezy/redux-persist-expo-securestore#1]
Hey,

Looks like the name of the remove item method in Expo is `deleteItemAsync` rather than `removeItemAsync`

https://github.com/expo/expo-sdk/blob/1fae0eed61c892d38d600daf23bf3c80cc9bea40/src/SecureStore.js#L27

**Comment by Cretezy** [comment]
Good catch, want to do a PR?

**Comment by samblacklock** [comment]
Sorry for the delay - PR open

**Comment by Cretezy** [comment]
Merged! Thank you
