### ISSUE TITLE
Getting error _expo.SecureStore.removeItemAsync is not a function

### ISSUE THREAD

**Issue by osdiab** [Cretezy/redux-persist-expo-securestore#4]
This seems to occur when I install via:

```
yarn add redux-persist-expo-securestore
```

It looks like it was changed in the source, but maybe that wasn't updated in npm? Thanks!

**Comment by Cretezy** [comment]
That's odd. The error is showing that it's Expo's fault, can you provide a full error log and reproducable code sample?

**Comment by osdiab** [comment]
Yeah, the error is below from the simulator, you can make it happen by calling `persistor.purge()`.

It's worth noting that if you look at the library's `index.js` in `node_modules`, you'll see it's calling `removeItemAsync`, but if you look at the source code in `master`, it calls `deleteItemAsync`, which is consistent with the [Expo docs](https://docs.expo.io/versions/latest/sdk/securestore#exposecurestoredeleteitemasynckey-options). Additionally, in `node_modules` it says the version of the library is `1.0.0`, but master here is `0.1.0`. Looks like the repo has diverged from what's distributed in NPM.

<img width="365" alt="screen shot 2018-06-07 at 6 28 20 pm" src="https://user-images.githubusercontent.com/1890926/41129549-99cedba0-6a80-11e8-8847-5d140ec79a5e.png">

**Comment by osdiab** [comment]
All you need to do to see the erroneous code is to initialize a node package and install the library, then look in `node_modules` and you'll see it's messed. Alternatively look at what's tagged as 1.0.0 in this repo and it's wrong too.

**Comment by Cretezy** [comment]
Yeah there's definitely something funky going on. I'll take a look soon.

**Comment by skibz** [comment]
It appears as though a new version was published. Does this mean this issue is resolved?

**Comment by Cretezy** [comment]
This should be fixed once https://github.com/Cretezy/redux-persist-expo-securestore/pull/8 is merge

**Comment by Cretezy** [comment]
I've just published `v2.0.0` with #8. Please test again and open if is it still broken
